// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmNk-6sYAerfUS3Ie-tgfKsKEi-PkVJ9g',
    appId: '1:778048144943:web:2f057fa0baf04d25b628da',
    messagingSenderId: '778048144943',
    projectId: 'skyfast-1a0d3',
    authDomain: 'skyfast-1a0d3.firebaseapp.com',
    storageBucket: 'skyfast-1a0d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjG3oxA9_-88RrI603eEFjArnTeWWp4cs',
    appId: '1:778048144943:android:872fd7a57b6627f6b628da',
    messagingSenderId: '778048144943',
    projectId: 'skyfast-1a0d3',
    storageBucket: 'skyfast-1a0d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgAcCAIBYanz3j0BgwCoakFsO3mIuvsE',
    appId: '1:778048144943:ios:8e2185f364c13b71b628da',
    messagingSenderId: '778048144943',
    projectId: 'skyfast-1a0d3',
    storageBucket: 'skyfast-1a0d3.appspot.com',
    iosBundleId: 'com.example.davisTravel',
  );
}
